(function(){
"use strict";
const E=window.MustangEngine,R=window.MustangRecords;
const canvas=document.getElementById("board"),ctx=canvas.getContext("2d");
let board=null,state="idle",selected=null,legalMoves=[],moveCount=0,moveHistory=[],selectedLevel=32,elapsed=0,startedAt=null,timer=null,aiBusy=false;
let undoStack=[],undoUsed=false,initialKnight=null,initialNumBishops=0;
let recSrc="local",recSort="time",recLevel=32,worldCache=[];
let replayMoves=[],replayIndex=0,replayTimer=null,replayBackup=null,replayMeta=null;
let campaignType=null,campaignName="",campaignPassword="",campaignTotalMoves=0,campaignTotalTime=0,campaignLevelStart=0,campaignMarathonStart=0,campaignNextLevel=0;
let autoSeries=false,autoSeriesNo=0,autoSeriesTotal=20,autoTargetBishops=32,autoTimer=null,autoPositionHistory=[],autoRoundHistory=[],autoPendingBishop=null;
let currentRecord=null,recordSaved=false;
const SAVE_KEY="mustang_mobile_v21_save";
const CAMP_KEY="mustang_mobile_v21_campaigns";
const LEVEL_LIMIT=500,STEPS_LIMIT=2026,MARATHON_LIMIT=2*3600+26*60;

function msg(t,cls){const e=document.getElementById("message");e.textContent=t||"";e.className=cls||""}
function nowSec(){return performance.now()/1000}
function currentElapsed(){return elapsed+(startedAt==null?0:Math.max(0,nowSec()-startedAt))}
function startTimer(){stopTimer();timer=setInterval(function(){if(state==="playing"){updateStats();checkLimits()}},200)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function updateStats(){document.getElementById("st-b").textContent=board?board.numBishops:"—";document.getElementById("st-m").textContent=moveCount;document.getElementById("st-t").textContent=currentElapsed().toFixed(1)}
function setModeLabel(){document.getElementById("mode-label").textContent=campaignType?("Кампанія · "+campaignTitle(campaignType)):"Швидка гра"}
function campaignTitle(t){return{summit:"Вершина",steps2026:"2026 кроків",marathon:"Марафон"}[t]||t}
function boardData(b){return{numBishops:b.numBishops,grid:b.grid.map(r=>r.slice()),bishops:b.bishops.map(x=>x.slice()),knight:b.knight&&b.knight.slice()}}
function boardFromData(d){const b=new E.Board(d.numBishops||16);b.grid=d.grid.map(r=>r.slice());b.bishops=(d.bishops||[]).map(x=>x.slice());b.knight=d.knight&&d.knight.slice();b.numBishops=d.numBishops||b.bishops.length;return b}
function snapshot(){return{board:boardData(board),moveCount,moveHistory:moveHistory.slice(),elapsed:currentElapsed(),undoUsed}}
function restore(s){board=boardFromData(s.board);moveCount=s.moveCount||0;moveHistory=s.moveHistory||[];elapsed=Number(s.elapsed)||0;undoUsed=!!s.undoUsed;selected=null;legalMoves=[];aiBusy=false}
function saveQuick(silent){if(!board)return false;if(!silent&&state==="playing"){elapsed=currentElapsed();startedAt=null;state="paused";selected=null;legalMoves=[];stopTimer()}try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:21,savedAt:Date.now(),selectedLevel,board:boardData(board),moveCount,moveHistory,elapsed,undoStack:undoStack.slice(-30),undoUsed,initialKnight,initialNumBishops}));if(!silent)msg("Гру збережено. На паузі.","pause");updateButtons();draw();return true}catch(e){if(!silent)msg("Не вдалося зберегти");return false}}
function hasSave(){try{return !!localStorage.getItem(SAVE_KEY)}catch(e){return false}}
function clearSave(){try{localStorage.removeItem(SAVE_KEY)}catch(e){}updateButtons()}
function loadQuick(){let raw;try{raw=localStorage.getItem(SAVE_KEY)}catch(e){raw=null}if(!raw){msg("Немає збереженої партії");return}let d;try{d=JSON.parse(raw)}catch(e){clearSave();msg("Збереження пошкоджене");return}stopTimer();state="paused";board=boardFromData(d.board);selectedLevel=Number(d.selectedLevel||board.numBishops);moveCount=Number(d.moveCount)||0;moveHistory=Array.isArray(d.moveHistory)?d.moveHistory.slice():[];elapsed=Number(d.elapsed)||0;undoStack=Array.isArray(d.undoStack)?d.undoStack:[];undoUsed=!!d.undoUsed;initialKnight=d.initialKnight||board.knight;initialNumBishops=Number(d.initialNumBishops||board.numBishops);clearSave();startedAt=null;campaignType=null;setModeLabel();msg("Збереження відновлено. Натисніть «Пауза»/«Продовжити».","pause");syncLevelButtons();updateStats();updateButtons();draw()}
function undoMove(){if(aiBusy||autoSeries){msg("Автоматичний хід ще не завершено");return}if(!undoStack.length){msg("Немає ходів для відміни");return}if(!confirm("При відміні ходу рекорд не буде зараховано. Відмінити хід?"))return;restore(undoStack.pop());undoUsed=true;if(state==="finished")state="playing";if(state==="playing"){startedAt=nowSec();startTimer()}msg("З поверненням ходів","undo-red");updateStats();updateButtons();draw();saveQuick(true)}
function updateButtons(){document.getElementById("btn-pause").disabled=!(board&&(state==="playing"||state==="paused"))||autoSeries;document.getElementById("btn-save").disabled=!(board&&(state==="playing"||state==="paused"))||autoSeries;document.getElementById("btn-continue").disabled=!hasSave();document.getElementById("btn-undo").disabled=!(board&&undoStack.length&&!aiBusy&&state!=="idle")||autoSeries;document.getElementById("btn-notation").disabled=!moveHistory.length}
function syncLevelButtons(){document.querySelectorAll(".lvl").forEach(b=>b.classList.toggle("active",Number(b.dataset.n)===selectedLevel))}
function ordered(n){let a=[];for(let r=7;r>=0;r--)for(let c=0;c<8;c++)a.push([r,c]);return a.slice(0,Math.max(1,Math.min(n,63)))}
function cloneBoard(b){const x=new E.Board(1);x.numBishops=b.numBishops;x.grid=b.grid.map(r=>r.slice());x.bishops=b.bishops.map(p=>p.slice());x.knight=b.knight&&b.knight.slice();return x}
function sig(b){return JSON.stringify([b.bishops.slice().sort((a,c)=>a[0]-c[0]||a[1]-c[1]),b.knight])}
function repeatedPosition(hist,cand){for(let n=2;n<=5;n++)if(hist.length>=n&&hist[hist.length-n]===cand)return n;return null}
function repeatedRound(hist,cand){const s=hist.concat([cand]);for(let n=2;n<=5;n++)if(s.length>=2*n){let a=s.slice(-n),b=s.slice(-2*n,-n);if(JSON.stringify(a)===JSON.stringify(b))return n}return null}
function bestBishopMoveAI(b,posHist,roundHist,report){let candidates=[];for(const [br,bc] of b.bishops.slice()){for(const [tr,tc] of b.bishopMoves(br,bc)){const t=cloneBoard(b);t.move(br,bc,tr,tc);const mob=t.knightMobility();const center=Math.abs(t.knight[0]-3.5)+Math.abs(t.knight[1]-3.5);candidates.push({mob,center,fr:[br,bc],to:[tr,tc],after:t})}}if(!candidates.length)return null;let ok=[];let blocked=[];for(const c of candidates){const k=E.bestKnightMove(c.after);if(!k){ok.push(c);continue}const p=cloneBoard(c.after),fr=p.knight.slice();p.move(fr[0],fr[1],k[0],k[1]);const brTxt="B"+E.posToAlg(c.fr[0],c.fr[1])+"-"+E.posToAlg(c.to[0],c.to[1]);const nkTxt="N"+E.posToAlg(fr[0],fr[1])+"-"+E.posToAlg(k[0],k[1]);const cyc=repeatedRound(roundHist,[brTxt,nkTxt]),pc=repeatedPosition(posHist,sig(p));if(cyc)blocked.push(cyc);if(pc)blocked.push(pc);if(!cyc&&!pc)ok.push(c)}if(report)report.push.apply(report,[...new Set(blocked)]);const pool=ok.length?ok:candidates;pool.sort((a,b)=>a.mob-b.mob||a.center-b.center);return[pool[0].fr,pool[0].to]}
function resize(){const w=document.getElementById("board-wrap"),size=Math.max(220,Math.min(w.clientWidth,w.clientHeight||w.clientWidth,450));const d=window.devicePixelRatio||1;canvas.width=Math.round(size*d);canvas.height=Math.round(size*d);canvas.style.width=size+"px";canvas.style.height=size+"px";ctx.setTransform(d,0,0,d,0,0);canvas._size=size;canvas._d=d;canvas._margin=Math.max(10,size*.04);canvas._sq=(size-2*canvas._margin)/8;draw()}
function draw(){const size=canvas._size||400,m=canvas._margin||16,s=canvas._sq||46;ctx.clearRect(0,0,size,size);ctx.fillStyle="#312e2b";ctx.fillRect(0,0,size,size);for(let r=0;r<8;r++)for(let c=0;c<8;c++){ctx.fillStyle=(r+c)%2===0?"#f0d9b5":"#b58863";ctx.fillRect(m+c*s,m+r*s,s+.5,s+.5)}if(state==="playing"&&legalMoves.length)legalMoves.forEach(p=>{ctx.beginPath();ctx.arc(m+p[1]*s+s/2,m+p[0]*s+s/2,s*.16,0,Math.PI*2);ctx.fillStyle="rgba(90,160,220,.7)";ctx.fill()});if(selected){ctx.strokeStyle="#77dd77";ctx.lineWidth=Math.max(3,s*.06);ctx.strokeRect(m+selected[1]*s+2,m+selected[0]*s+2,s-4,s-4)}if(board&&state!=="paused"){for(const [r,c] of board.bishops){piece(r,c,"B")}if(board.knight)piece(board.knight[0],board.knight[1],"N")}else if(board){ctx.fillStyle="#0008";ctx.fillRect(m,m,8*s,8*s);ctx.fillStyle="#f0d9b5";ctx.font="bold "+Math.round(s*.55)+"px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("ПАУЗА",m+4*s,m+4*s)}ctx.fillStyle="#777";ctx.font=Math.max(9,Math.round(s*.2))+"px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";for(let c=0;c<8;c++)ctx.fillText(String.fromCharCode(97+c),m+c*s+s/2,m+8*s+m*.45);for(let r=0;r<8;r++)ctx.fillText(String(8-r),m*.4,m+r*s+s/2)}
function piece(r,c,t){const m=canvas._margin,s=canvas._sq,cx=m+c*s+s/2,cy=m+r*s+s/2;ctx.beginPath();ctx.arc(cx,cy,s*.34,0,Math.PI*2);ctx.fillStyle=t==="B"?"#f5f0e6":"#1c1917";ctx.fill();ctx.strokeStyle=t==="B"?"#333":"#eee";ctx.stroke();ctx.fillStyle=t==="B"?"#1c1917":"#f0d9b5";ctx.font="bold "+Math.round(s*.4)+"px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(t,cx,cy+1)}
function cell(e){const r=canvas.getBoundingClientRect(),x=e.changedTouches?e.changedTouches[0].clientX-r.left:e.clientX-r.left,y=e.changedTouches?e.changedTouches[0].clientY-r.top:e.clientY-r.top,scale=(canvas.width/(canvas._d||1))/r.width,m=canvas._margin||16,s=canvas._sq||1;return{c:Math.floor((x*scale-m)/s),r:Math.floor((y*scale-m)/s)}}
function pointer(e){e.preventDefault();if(state!=="playing"||aiBusy||autoSeries||!board)return;const p=cell(e),r=Math.floor(p.r),c=Math.floor(p.c);if(r<0||r>7||c<0||c>7)return;if(selected&&legalMoves.some(x=>x[0]===r&&x[1]===c)){playerBishopMove(selected[0],selected[1],r,c);return}selected=null;legalMoves=[];if(board.grid[r][c]===E.BISHOP){selected=[r,c];legalMoves=board.bishopMoves(r,c);msg(legalMoves.length?"Оберіть клітинку для ходу":"У цього слона немає ходу");draw()}else{msg("Оберіть слона");draw()}}
function pushUndo(){undoStack.push(snapshot());if(undoStack.length>60)undoStack.shift()}
function playerBishopMove(fr,fc,tr,tc){pushUndo();board.move(fr,fc,tr,tc);moveHistory.push("B"+E.posToAlg(fr,fc)+"-"+E.posToAlg(tr,tc));moveCount++;selected=null;legalMoves=[];updateStats();draw();if(checkLimits())return;if(E.isKnightCaught(board)){finishGame();return}aiBusy=true;msg("Кінь думає…");setTimeout(function(){const mv=E.bestKnightMove(board);if(!mv){aiBusy=false;finishGame();return}const [kr,kc]=board.knight;board.move(kr,kc,mv[0],mv[1]);moveHistory.push("N"+E.posToAlg(kr,kc)+"-"+E.posToAlg(mv[0],mv[1]));aiBusy=false;msg(E.posToAlg(kr,kc)+" → "+E.posToAlg(mv[0],mv[1]));updateStats();draw();if(E.isKnightCaught(board))finishGame()},90)}
function startGame(n){stopAuto();hide("win-panel");hide("records-panel");hide("notation-panel");selectedLevel=n;syncLevelButtons();campaignType=null;campaignTotalMoves=0;campaignTotalTime=0;setModeLabel();clearSave();undoStack=[];undoUsed=false;board=new E.Board(n);state="playing";selected=null;legalMoves=[];moveCount=0;moveHistory=[];elapsed=0;startedAt=nowSec();initialKnight=board.knight&&board.knight.slice();initialNumBishops=n;currentRecord=null;recordSaved=false;setMsg("Натисніть на слона");document.getElementById("ai-status").textContent="";document.getElementById("campaign-banner").textContent="";updateStats();updateButtons();draw();startTimer()}
function togglePause(){if(autoSeries||!board)return;if(state==="playing"){elapsed=currentElapsed();startedAt=null;state="paused";selected=null;legalMoves=[];stopTimer();msg("Пауза — фігури приховано.","pause");draw()}else if(state==="paused"){startedAt=nowSec();state="playing";msg("Гру продовжено");startTimer();draw();updateStats()}}
function startAuto(){if(!board||state==="idle"||campaignType){if(campaignType)msg("Для кампанії GPT запускає лише поточну партію.");else msg("Спочатку натисніть «Нова гра».");return}stopAuto();autoSeries=true;autoSeriesNo=1;autoSeriesTotal=20;autoTargetBishops=selectedLevel;document.getElementById("btn-ai").textContent="Стоп GPT";msg("GPT#1/20 запускається");updateButtons();runAutoGame()}
function stopAuto(){autoSeries=false;if(autoTimer){clearTimeout(autoTimer);autoTimer=null}document.getElementById("btn-ai").textContent="GPT ×20";updateButtons()}
function runAutoGame(){if(!autoSeries)return;board=new E.Board(autoTargetBishops);state="playing";selected=null;legalMoves=[];moveCount=0;moveHistory=[];elapsed=0;startedAt=nowSec();undoStack=[];undoUsed=false;autoPositionHistory=[sig(board)];autoRoundHistory=[];autoPendingBishop=null;initialKnight=board.knight&&board.knight.slice();initialNumBishops=board.numBishops;document.getElementById("ai-status").textContent="GPT#"+autoSeriesNo+"/20 · слонів "+autoTargetBishops;updateStats();draw();autoTimer=setTimeout(autoBishopTurn,220)}
function autoBishopTurn(){if(!autoSeries)return;const report=[],mh=bestBishopMoveAI(board,autoPositionHistory,autoRoundHistory,report);if(!mh){finishAutoGame();return}const fr=mh[0],to=mh[1];autoPendingBishop="B"+E.posToAlg(fr[0],fr[1])+"-"+E.posToAlg(to[0],to[1]);board.move(fr[0],fr[1],to[0],to[1]);moveHistory.push(autoPendingBishop);moveCount++;document.getElementById("ai-status").textContent="GPT#"+autoSeriesNo+"/20 · хід "+moveCount+(report.length?" · CycleGuard "+[...new Set(report)].join(","):"");draw();if(E.isKnightCaught(board)){finishAutoGame();return}autoTimer=setTimeout(autoKnightTurn,120)}
function autoKnightTurn(){if(!autoSeries)return;const mv=E.bestKnightMove(board);if(!mv){finishAutoGame();return}const [kr,kc]=board.knight;const nt="N"+E.posToAlg(kr,kc)+"-"+E.posToAlg(mv[0],mv[1]);board.move(kr,kc,mv[0],mv[1]);moveHistory.push(nt);if(autoPendingBishop){autoRoundHistory.push([autoPendingBishop,nt]);autoPendingBishop=null}autoPositionHistory.push(sig(board));draw();if(E.isKnightCaught(board)){finishAutoGame();return}autoTimer=setTimeout(autoBishopTurn,120)}
function finishAutoGame(){if(!autoSeries)return;elapsed=currentElapsed();startedAt=null;stopTimer();const rec={name:"GPT#"+autoSeriesNo,bishops:autoTargetBishops,moves:moveCount,time_sec:elapsed,notation:E.formatGameNotation(moveHistory),knight_start:initialKnight?E.posToAlg(initialKnight[0],initialKnight[1]):"",date:new Date().toISOString(),timestamp:Date.now()/1000,score:E.parityScore(autoTargetBishops,moveCount,elapsed)};if(R)R.addLocal(rec);const done=autoSeriesNo;if(done>=autoSeriesTotal){autoSeries=false;state="finished";document.getElementById("btn-ai").textContent="GPT ×20";document.getElementById("ai-status").textContent="Серію GPT#1–GPT#20 завершено";msg("Серію завершено","win");updateStats();updateButtons();draw();return}autoSeriesNo++;msg("GPT#"+done+" завершено → GPT#"+autoSeriesNo+"/20");autoTimer=setTimeout(runAutoGame,300)}
function campaignDesc(t){return{summit:"32→1. На рівні: максимум 500 ходів або час (32−N)×60+120 с.",steps2026:"32→1. Один спільний ліміт: 2026 ходів.",marathon:"32→1. Один спільний ліміт часу: 2 год 26 хв."}[t]}
function allCamps(){try{return JSON.parse(localStorage.getItem(CAMP_KEY)||"{}")}catch(e){return{}}}
function campKey(t,n,p){return[t,(n||"Гравець").trim().toLowerCase(),p||""].join("::")}
function getCamp(t,n,p){return allCamps()[campKey(t,n,p)]||null}
function setCamp(d){const a=allCamps();a[campKey(d.type,d.name,d.password)]=d;localStorage.setItem(CAMP_KEY,JSON.stringify(a))}
function resetCamp(t,n,p){const a=allCamps();delete a[campKey(t,n,p)];localStorage.setItem(CAMP_KEY,JSON.stringify(a))}
function refreshCamp(){const n=(document.getElementById("camp-name").value||"").trim()||"Гравець",p=document.getElementById("camp-password").value||"",d=getCamp(selectedCamp,n,p);document.getElementById("campaign-desc").textContent=campaignDesc(selectedCamp);document.getElementById("camp-status").textContent=d?(d.status==="ongoing"?"Збережено: "+d.numBishops+" сл. · "+d.totalMoves+" ходів · "+Number(d.totalTime).toFixed(1)+" с":"Кампанію вже завершено на "+d.numBishops+" сл."):"Новий старт: 32 слони"}
let selectedCamp="summit";
function openCampaigns(){show("campaigns-panel");if(R&&!document.getElementById("camp-name").value)document.getElementById("camp-name").value=R.getPlayerName()||"";refreshCamp()}
function startCampaign(){const n=(document.getElementById("camp-name").value||"").trim()||"Гравець",p=document.getElementById("camp-password").value||"";if(!p){msg("Для кампанії введіть пароль");return}const existing=getCamp(selectedCamp,n,p);campaignType=selectedCamp;campaignName=n;campaignPassword=p;campaignTotalMoves=existing?Number(existing.totalMoves)||0:0;campaignTotalTime=existing?Number(existing.totalTime)||0:0;campaignMarathonStart=existing&&existing.marathonStart?Number(existing.marathonStart):Date.now()/1000;const nB=existing?Number(existing.numBishops)||32:32;setModeLabel();hide("campaigns-panel");startCampaignLevel(nB)}
function startCampaignLevel(nB){clearSave();stopAuto();board=new E.Board(nB);state="playing";selected=null;legalMoves=[];moveCount=0;moveHistory=[];elapsed=0;startedAt=nowSec();campaignLevelStart=0;initialKnight=board.knight&&board.knight.slice();initialNumBishops=nB;undoStack=[];undoUsed=false;msg("Кампанія: "+campaignTitle(campaignType)+" · "+nB+" слонів");updateCampaignBanner();updateStats();updateButtons();draw();startTimer()}
function currentLevelLimit(){return campaignType==="summit"?(32-board.numBishops)*60+120:Infinity}
function updateCampaignBanner(){const el=document.getElementById("campaign-banner");if(!campaignType){el.textContent="";return}let s=campaignTitle(campaignType)+" · "+board.numBishops+" сл. · Σ "+campaignTotalMoves+" ходів";if(campaignType==="steps2026")s+=" · залишок "+Math.max(0,STEPS_LIMIT-campaignTotalMoves-moveCount);if(campaignType==="marathon")s+=" · "+formatDuration(Math.max(0,MARATHON_LIMIT-(Date.now()/1000-campaignMarathonStart)));if(campaignType==="summit")s+=" · рівень "+Math.ceil(Math.max(0,currentLevelLimit()-currentElapsed()))+" с";el.textContent=s}
function checkLimits(){if(!campaignType||!board||state!=="playing")return false;updateCampaignBanner();if(moveCount>=LEVEL_LIMIT){campaignLose("Вичерпано 500 ходів на рівні.");return true}if(campaignType==="steps2026"&&campaignTotalMoves+moveCount>=STEPS_LIMIT){campaignLose("Вичерпано ліміт 2026 ходів.");return true}if(campaignType==="marathon"&&Date.now()/1000-campaignMarathonStart>=MARATHON_LIMIT){campaignLose("Вичерпано час марафону.");return true}if(campaignType==="summit"&&currentElapsed()>=currentLevelLimit()){campaignLose("Вичерпано час рівня.");return true}return false}
function campaignLose(reason){if(state!=="playing")return;campaignTotalMoves+=moveCount;campaignTotalTime+=currentElapsed();state="finished";startedAt=null;stopTimer();setCamp({type:campaignType,name:campaignName,password:campaignPassword,numBishops:board.numBishops,totalMoves:campaignTotalMoves,totalTime:campaignTotalTime,marathonStart:campaignMarathonStart,status:"finished",savedAt:Date.now()});msg("Кампанію завершено: "+reason);alert(reason+"\n\nЗбережено прогрес кампанії. Її можна продовжити тим самим ім'ям і паролем.")}
function finishGame(){state="finished";if(startedAt!=null){elapsed=currentElapsed();startedAt=null}stopTimer();clearSave();const score=E.parityScore(board.numBishops,moveCount,elapsed);msg("Кінь спійманий!","win");currentRecord={name:"Гравець",bishops:board.numBishops,moves:moveCount,time_sec:elapsed,notation:E.formatGameNotation(moveHistory),knight_start:initialKnight?E.posToAlg(initialKnight[0],initialKnight[1]):"",timestamp:Date.now()/1000,date:new Date().toISOString(),score};campaignNextLevel=0;if(campaignType){campaignTotalMoves+=moveCount;campaignTotalTime+=elapsed;const completed=board.numBishops;const next=completed-1;campaignNextLevel=next;setCamp({type:campaignType,name:campaignName,password:campaignPassword,numBishops:next,totalMoves:campaignTotalMoves,totalTime:campaignTotalTime,marathonStart:campaignMarathonStart,status:next<1?"finished":"ongoing",savedAt:Date.now()});showWin(score);return}showWin(score)}
function checkWinAfterCampaign(){if(campaignType&&board.numBishops<=1)finishGame()}
function showWin(score){document.getElementById("win-text").textContent=(campaignType?"Кампанія · ":"")+"Слонів: "+board.numBishops+"\nХодів: "+moveCount+"\nЧас: "+elapsed.toFixed(1)+" с\nОцінка: "+Number(score||0).toFixed(1)+(undoUsed?"\nЗастосовано відміну ходу — рекорд буде позначений *":"");document.getElementById("btn-again").textContent=campaignType?(campaignNextLevel>=1?"Наступний рівень":"Ще раз"):"Ще раз";document.getElementById("win-name").value=(R&&R.getPlayerName())||"";document.getElementById("win-status").textContent=undoUsed?"Результат із відміною ходу.":"";document.getElementById("win-panel").classList.remove("hidden");updateButtons()}
function hideWin(){hide("win-panel")}
async function saveRecord(){if(!currentRecord||recordSaved)return;let name=(document.getElementById("win-name").value||"").trim()||"Гравець";if(name.toLowerCase()==="гість"||name.toLowerCase()==="guest"){document.getElementById("win-status").textContent="Для світового рекорду введіть інше ім'я";return}if(R)R.setPlayerName(name);if(undoUsed)name+="*";const rec=Object.assign({},currentRecord,{name,undid:undoUsed});if(R)R.addLocal(rec);document.getElementById("win-status").textContent="Збережено на пристрої…";const w=R?await R.submitWorld(rec):null;document.getElementById("win-status").textContent=w&&w.ok?"Збережено на пристрої та у світі":"Збережено на пристрої";recordSaved=true}
function openRecords(){recLevel=selectedLevel;buildRecLevels();show("records-panel");renderRecords()}
function buildRecLevels(){const w=document.getElementById("rec-levels");w.innerHTML="";[32,24,16,14,12].forEach(n=>{const b=document.createElement("button");b.textContent=n;b.className=n===recLevel?"active":"";b.onclick=()=>{recLevel=n;buildRecLevels();renderRecords()};w.appendChild(b)})}
async function renderRecords(){const list=document.getElementById("records-list");list.innerHTML='<div class="rec-empty">Завантаження…</div>';let src=[];if(recSrc==="world"){const w=R?await R.fetchWorld():null;src=w&&w.records?w.records:[]}else src=R?R.loadLocal():[];const arr=R?R.filterSort(src,recLevel,recSort,100):[];if(!arr.length){list.innerHTML='<div class="rec-empty">Немає записів</div>';return}const me=(R&&R.getPlayerName()||"").replace(/\*+$/,"").toLowerCase();list.innerHTML="";arr.forEach((r,i)=>{const row=document.createElement("div");row.className="rec-row"+(((r.name||"").replace(/\*+$/,"").toLowerCase()===me)?" me":"")+(r.undid?" undid":"");row.innerHTML="<span>"+(i+1)+"</span><span>"+esc(r.name)+"</span><span>"+recValue(r)+"</span>";row.onclick=()=>openNotation({history:r.notation,bishops:r.bishops,name:r.name});list.appendChild(row)})}
function recValue(r){if(recSort==="moves")return r.moves+" ходів";if(recSort==="worldscore")return Number(E.parityScore(r.bishops,r.moves,r.time_sec)).toFixed(1);return Number(r.time_sec).toFixed(1)+" с"}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function openNotation(o){const toks=Array.isArray(o.history)?o.history:String(o.history||"").match(/[BN][a-h][1-8]-[a-h][1-8]/gi)||[];let k0=null;for(const t of toks){if(t[0].toUpperCase()==="N"){k0=algPos(t.slice(1,3));break}};if(!k0&&board&&board.knight)k0=board.knight.slice();replayMoves=toks;replayIndex=toks.length;replayMeta={bishops:Number(o.bishops||selectedLevel),knight:k0};document.getElementById("notation-meta").textContent=(o.name||"")+" · "+replayMoves.length+" півходів";document.getElementById("notation-text").textContent=E.formatGameNotation(replayMoves)||"(порожньо)";document.getElementById("notation-panel").classList.remove("hidden");showReplay(replayMoves.length)}
function algPos(a){return[a?8-Number(a[1]):0,a?a.charCodeAt(0)-97:0]}
function applyTok(b,t){const m=t.match(/^([BN])([a-h][1-8])-([a-h][1-8])$/i);if(!m)return;const fr=algPos(m[2]),to=algPos(m[3]);b.move(fr[0],fr[1],to[0],to[1])}
function showReplay(i){if(!replayMeta||!replayMeta.knight)return;stopReplay();i=Math.max(0,Math.min(i,replayMoves.length));replayIndex=i;const b=new E.Board(replayMeta.bishops);b.grid=Array.from({length:8},()=>Array(8).fill(E.EMPTY));b.bishops=ordered(replayMeta.bishops);for(const p of b.bishops)b.grid[p[0]][p[1]]=E.BISHOP;let k=replayMeta.knight.slice();if(b.grid[k[0]][k[1]]!==E.EMPTY){k=b.grid.flatMap((row,r)=>row.map((v,c)=>[r,c,v])).find(x=>x[2]===E.EMPTY).slice(0,2)}b.knight=k;b.grid[k[0]][k[1]]=E.KNIGHT;replayBackup=board;board=b;replayDraw();document.getElementById("notation-step").textContent="Хід "+i+" / "+replayMoves.length}
function replayDraw(){draw()}
function stopReplay(){if(replayTimer){clearInterval(replayTimer);replayTimer=null}document.getElementById("rep-play").textContent="▶"}
function closeNotation(){stopReplay();hide("notation-panel");if(replayBackup){board=replayBackup;replayBackup=null}draw()}
function rep(dir){showReplay(replayIndex+dir)}
function repPlay(){if(replayTimer){stopReplay();return}if(replayIndex>=replayMoves.length)showReplay(0);replayTimer=setInterval(()=>{if(replayIndex>=replayMoves.length){stopReplay();return}showReplay(replayIndex+1)},700);document.getElementById("rep-play").textContent="❚❚"}
function formatDuration(s){s=Math.max(0,Math.floor(s));let h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return(h?String(h).padStart(2,"0")+":":"")+String(m).padStart(2,"0")+":"+String(x).padStart(2,"0")}
function show(id){document.getElementById(id).classList.remove("hidden")}
function hide(id){document.getElementById(id).classList.add("hidden")}

document.querySelectorAll(".lvl").forEach(b=>b.onclick=()=>{selectedLevel=Number(b.dataset.n);syncLevelButtons()});
document.getElementById("btn-custom").onclick=()=>{const n=Number(prompt("Введіть кількість слонів 1–32",String(selectedLevel)));if(n>=1&&n<=32){selectedLevel=n;syncLevelButtons()}}
document.getElementById("btn-new").onclick=()=>startGame(selectedLevel);
document.getElementById("btn-ai").onclick=()=>autoSeries?stopAuto():startAuto();
document.getElementById("btn-pause").onclick=togglePause;
document.getElementById("btn-save").onclick=()=>saveQuick(false);
document.getElementById("btn-continue").onclick=loadQuick;
document.getElementById("btn-undo").onclick=undoMove;
document.getElementById("btn-records").onclick=openRecords;
document.getElementById("btn-records-close").onclick=()=>hide("records-panel");
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");recSrc=b.dataset.src;renderRecords()});
document.querySelectorAll(".sort").forEach(b=>b.onclick=()=>{document.querySelectorAll(".sort").forEach(x=>x.classList.remove("active"));b.classList.add("active");recSort=b.dataset.sort;renderRecords()});
document.getElementById("btn-notation").onclick=()=>openNotation({history:moveHistory,bishops:board?board.numBishops:selectedLevel,name:"Поточна партія"});
document.getElementById("btn-win-notation").onclick=()=>openNotation({history:currentRecord?currentRecord.notation:moveHistory,bishops:board?board.numBishops:selectedLevel,name:document.getElementById("win-name").value});
document.getElementById("btn-notation-close").onclick=closeNotation;
document.getElementById("rep-start").onclick=()=>showReplay(0);
document.getElementById("rep-prev").onclick=()=>rep(-1);
document.getElementById("rep-play").onclick=repPlay;
document.getElementById("rep-next").onclick=()=>rep(1);
document.getElementById("rep-end").onclick=()=>showReplay(replayMoves.length);
document.getElementById("btn-again").onclick=()=>{hideWin();if(campaignType){startCampaignLevel(campaignNextLevel>=1?campaignNextLevel:board.numBishops)}else{startGame(Math.max(1,board.numBishops-1))}};
document.getElementById("btn-win-close").onclick=hideWin;
document.getElementById("btn-save-record").onclick=saveRecord;
document.getElementById("btn-campaigns").onclick=openCampaigns;
document.getElementById("btn-campaigns-close").onclick=()=>hide("campaigns-panel");
document.getElementById("btn-camp-start").onclick=startCampaign;
document.getElementById("btn-camp-reset").onclick=()=>{const n=(document.getElementById("camp-name").value||"").trim()||"Гравець",p=document.getElementById("camp-password").value||"";if(confirm("Скинути кампанію?")){resetCamp(selectedCamp,n,p);refreshCamp()}};
document.querySelectorAll(".camp").forEach(b=>b.onclick=()=>{selectedCamp=b.dataset.type;document.querySelectorAll(".camp").forEach(x=>x.classList.toggle("active",x===b));refreshCamp()});
document.getElementById("camp-name").oninput=refreshCamp;document.getElementById("camp-password").oninput=refreshCamp;
canvas.addEventListener("click",pointer);canvas.addEventListener("touchend",pointer,{passive:false});
window.addEventListener("resize",resize);window.addEventListener("orientationchange",()=>setTimeout(resize,150));
resize();updateButtons();updateStats();
})();